services:
  - type: web
    name: omboa-gateway
    runtime: python
    repo: https://github.com/ebengetaba-Anck/globetrotter-capstone
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn services.gateway_service:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: USER_SERVICE_URL
        value: http://localhost:5001
      - key: ITINERARY_SERVICE_URL
        value: http://localhost:5002
      - key: RECOMMENDATION_SERVICE_URL
        value: http://localhost:5003